name: Continuous Integration

on:
  workflow_call:
    inputs:
      release:
        required: false
        type: boolean
    secrets:
      WF_TOKEN:
        required: true
      NPM_TOKEN:
        required: false

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          scope: "@wonderflow"

      - name: Update NPM to v8
        run: npm i -g npm@8

      - name: Cache Dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-node-npm
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        if: inputs.release == true
        with:
          version: ./update-lock.sh
          publish: npm run release
          commit: "ci: release"
          title: "ci: release"
        env:
          GITHUB_TOKEN: ${{ secrets.WF_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
