name: Continuous Integration

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: wonderflow-bv/stylelint-config-wonderflow/.github/workflows/ci-workflow.yml@main
    secrets:
      WF_TOKEN: ${{ secrets.WONDERFLOW_WORKFLOW_TOKEN }}
