name: Release

on: workflow_dispatch

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"
          scope: "@wonderflow"

      - run: npm i -g npm@8

      - name: Cache Dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-node-npm
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        run: npm install

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.WONDERFLOW_WORKFLOW_TOKEN }}
          NPM_TOKEN: ${{ secrets.WONDERFLOW_NPM_TOKEN }}
        run: npm run release
